tasks/ajax/urls.py
from django.conf.urls import url

from .views import (
    TaskCreateAjaxView,
    TaskUpdateAjaxView,
    TaskDoneAjaxView,
    TaskDeleteAjaxView
)

urlpatterns = [
    url(r'^create/$', TaskCreateAjaxView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/edit/$', TaskUpdateAjaxView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/done/$', TaskDoneAjaxView.as_view(), name='done'),
    url(r'^(?P<pk>\d+)/delete/$', TaskDeleteAjaxView.as_view(), name='delete'),
]

tasks/api/urls.py
from django.conf.urls import url

from .views import TaskViewSet

COLLECTION_ACTIONS = {
    'get': 'list',
    'post': 'create'
}

OBJECT_ACTIONS = {
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
}

urlpatterns = [
    url(r'^$', TaskViewSet.as_view(COLLECTION_ACTIONS), name='list'),
    url(r'^(?P<pk>\d+)/$', TaskViewSet.as_view(OBJECT_ACTIONS), name='detail')
]

tasks/urls.py
from django.conf.urls import url

from .views import (
    TaskCreateView,
    TasksListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView
)

urlpatterns = [
    url(r'^$', TasksListView.as_view(), name='list'),
    url(r'^create/$', TaskCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', TaskDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', TaskUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', TaskDeleteView.as_view(), name='delete'),
]

todo/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from oauth2_provider.views import TokenView
from rest_framework_swagger.views import get_swagger_view

from .static import static

schema_view = get_swagger_view(title='Todo API')

# general
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^', include('tasks.urls'), name='tasks'),
]

# ajax
urlpatterns += [
    url(r'^ajax/tasks/', include('tasks.ajax.urls'), name='tasks-ajax'),
]

# API
urlpatterns += [
    url(r'^api/o/token/$', TokenView.as_view(), name='oauth2-token'),
    url(r'^api/docs/$', schema_view, name='api-docs'),
    url(r'^api/tasks/', include('tasks.api.urls'), name='tasks-api'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    description = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)  # when model was created
    updated = models.DateTimeField(auto_now=True)  # everytime the model is saved

    class Meta:
        permissions = (
            ('view_task', 'Can view tasks'),
        )

tasks/ajax/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render_to_response

from guardian.mixins import PermissionRequiredMixin
from guardian.shortcuts import assign_perm

from todo.mixins import (
    AjaxCreateMixin,
    AjaxUpdateMixin,
    AjaxDeleteMixin
)
from ..models import Task


class TaskCreateAjaxView(PermissionRequiredMixin, AjaxCreateMixin, CreateView):
    template_name = 'task_item.html'
    context_object_name = 'task'
    model = Task
    fields = ['description']
    permission_object = None
    permission_required = ['tasks.add_task']
    raise_exception = True

    def form_valid(self, form):
        form.instance.user = self.request.user
        resp = super().form_valid(form)
        assign_perm('tasks.view_task', self.request.user, self.object)
        assign_perm('tasks.change_task', self.request.user, self.object)
        assign_perm('tasks.delete_task', self.request.user, self.object)
        return resp


class TaskUpdateAjaxView(PermissionRequiredMixin, AjaxUpdateMixin, UpdateView):
    template_name = 'task_item.html'
    context_object_name = 'task'
    model = Task
    fields = ['description', 'is_done']
    permission_required = ['tasks.view_task', 'tasks.change_task']
    raise_exception = True


class TaskDoneAjaxView(PermissionRequiredMixin, AjaxUpdateMixin, UpdateView):
    template_name = 'task_item.html'
    context_object_name = 'task'
    model = Task
    fields = ['is_done']
    permission_required = ['tasks.view_task', 'tasks.change_task']
    raise_exception = True


class TaskDeleteAjaxView(PermissionRequiredMixin, AjaxDeleteMixin, DeleteView):
    model = Task
    permission_required = ['tasks.view_task', 'tasks.delete_task']
    raise_exception = True

tasks/api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import (
    DjangoObjectPermissionsFilter,
    SearchFilter,
    OrderingFilter
)
from rest_framework.permissions import DjangoModelPermissions
from django_filters.rest_framework import DjangoFilterBackend
from guardian.shortcuts import assign_perm

from ..models import Task
from .serializers import TaskSerializer
from .filters import TaskFilter
from .permissions import TasksObjectPermissions


class TaskViewSet(ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    filter_backends = [DjangoObjectPermissionsFilter,
                       DjangoFilterBackend,
                       OrderingFilter,
                       SearchFilter]
    ordering_fields = ['is_done', 'created', 'updated']
    search_fields = ['description']
    filter_class = TaskFilter
    permission_classes = [DjangoModelPermissions, TasksObjectPermissions]

    def perform_create(self, serializer):
        task = serializer.save(user=self.request.user)
        assign_perm('tasks.view_task', self.request.user, task)
        assign_perm('tasks.change_task', self.request.user, task)
        assign_perm('tasks.delete_task', self.request.user, task)

tasks/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from guardian.mixins import PermissionRequiredMixin, PermissionListMixin
from guardian.shortcuts import assign_perm

from .models import Task


# Create your views here.
class TaskCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'task_create.html'
    model = Task
    fields = ['description']
    success_url = '/'
    permission_object = None
    permission_required = ['tasks.add_task']
    raise_exception = True

    def form_valid(self, form):
        form.instance.user = self.request.user
        resp = super().form_valid(form)
        assign_perm('tasks.view_task', self.request.user, self.object)
        assign_perm('tasks.change_task', self.request.user, self.object)
        assign_perm('tasks.delete_task', self.request.user, self.object)
        return resp


class TasksListView(PermissionRequiredMixin, PermissionListMixin, ListView):
    template_name = 'tasks_index.html'
    context_object_name = 'tasks'
    model = Task
    permission_required = ['tasks.view_task']
    get_objects_for_user_extra_kwargs = {'accept_global_perms': False}


class TaskDetailView(PermissionRequiredMixin, DetailView):
    template_name = 'task_detail.html'
    context_object_name = 'task'
    model = Task
    permission_required = ['tasks.view_task']
    raise_exception = True


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'task_edit.html'
    model = Task
    fields = ['description', 'is_done']
    success_url = '/'
    permission_required = ['tasks.view_task', 'tasks.change_task']
    raise_exception = True


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'task_delete.html'
    context_object_name = 'task'
    model = Task
    success_url = '/'
    permission_required = ['tasks.view_task', 'tasks.delete_task']
    raise_exception = True

tasks/templates/task_create.html
{% extends "main.html" %}
{% block title %}Create task{% endblock %}
{% block main %}
    <div class="container">
        <div class="center-content">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary btn-block" type="submit">Add task</button>
            </form>
        </div>
    </div>
{% endblock %}

tasks/templates/task_delete.html
{% extends "main.html" %}
{% block title %}Delete task{% endblock %}
{% block main %}
    <div class="container">
        <div class="center-content">
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ task.description }}"?</p>
                <button class="btn btn-danger btn-block" type="submit">Delete</button>
                <a href="/" class="btn btn-default btn-block">No</a>
            </form>
        </div>
    </div>
{% endblock %}

tasks/templates/task_detail.html
{% extends "main.html" %}
{% block title %}Task detail{% endblock %}
{% block main %}
    <div class="container">
        <div class="center-content">
            <p>
                id: {{ task.id }}
            </p>
            <p>
                description: {{ task.description }}
            </p>
            <p>
                {% if task.is_done %}
                is done &#10004;
                {% else %}
                is not done &#10008;
                {% endif %}
            </p>
            <p>
                date: {{ task.created|date:"D d M Y" }}
            </p>
            <p>
                <a href="edit" class="btn btn-success btn-block">Edit</a>
                <a href="delete" class="btn btn-danger btn-block">Delete</a>
            </p>
        </div>
    </div>
{% endblock %}

tasks/templates/task_edit.html
{% extends "main.html" %}
{% block title %}Edit task{% endblock %}
{% block main %}
    <div class="container">
        <div class="center-content">
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success btn-block" type="submit">Update task</button>
            </form>
        </div>
    </div>
{% endblock %}

tasks/templates/task_item.html
<li id="task_{{task.id}}" class="list-group-item">
    <div class="checkbox">
        <input type="checkbox" id="task_is_done_{{task.id}}" data-id="{{task.id}}" {% if task.is_done %}
               checked="checked" {% endif %}/>
        <label for="task_is_done_{{task.id}}">{{task.description}}</label>
    </div>
    <div class="pull-right action-buttons">
        <a href="#" class="pencil" data-id="{{task.id}}" data-is-done="{{task.is_done|yesno:" true,false"}}"
        data-description="{{task.description}}"
        data-toggle="modal" data-target="#modal_edit"><span class="glyphicon glyphicon-pencil"></span></a>
        <a href="#" class="trash" data-id="{{task.id}}" data-toggle="modal"
           data-target="#modal_delete"><span class="glyphicon glyphicon-trash"></span></a>
    </div>
</li>

tasks/templates/tasks_index.html
{% extends "main.html" %}
{% load staticfiles %}
{% block additional_css %}
    {{ block.super }}
    <!--Tasks css-->
    <link type="text/css" href="{% static "tasks/css/tasks.css" %}" rel="stylesheet">
{% endblock %}
{% block title %}{{user}}{% endblock %}
{% block main %}
    <div class="container">
        <!--Error alert-->
        <div id="error_alert" class="alert alert-danger alert-dismissible fade in" role="alert" style="display:none;">
            <button type="button" class="close" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <h4 id="error_title"></h4>
            <p id="error_message"></p>
        </div>
        <!-- Add task form -->
        <form id="form_create" action="/create/" method="post">{% csrf_token %}
            <div class="input-group">
                <input id="id_description" maxlength="255" name="description" type="text" class="form-control"
                       placeholder="What needs to be done?">
                <div class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Add task</button>
                </div>
            </div>
        </form>
        <!-- Outstanding tasks -->
        <h3>Outstanding tasks</h3>
        <ul id="outstanding_tasks" class="list-group">
            {% for task in tasks %}
                {% if not task.is_done %}
                    {% include "task_item.html" %}
                {% endif %}
            {% endfor %}
        </ul>
        <!-- Completed tasks -->
        <h3>Completed tasks</h3>
        <ul id="completed_tasks" class="list-group checked-list-box">
            {% for task in tasks %}
                {% if task.is_done %}
                    {% include "task_item.html" %}
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    <!-- Edit task modal dialog -->
    <div class="modal fade" id="modal_edit">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal"><span aria-hidden="true">&times;</span>
                    </button>
                    <h4>Edit task</h4>
                </div>
                <div class="modal-body">
                    <form>{% csrf_token %}
                        <div class="form-group">
                            <label for="task_description" class="control-label">Description:</label>
                            <input type="text" class="form-control" id="task_description" maxlength="255"/>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-success btn-ok" type="button" data-dismiss="modal">Edit</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete task modal dialog -->
    <div class="modal fade" id="modal_delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal"><span aria-hidden="true">&times;</span>
                    </button>
                    <h4>Confirm delete</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure want delete this taks?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger btn-ok" type="button" data-dismiss="modal">Delete</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block additional_js %}
    {{ block.super }}
    <!-- Tasks script -->
    <script src="{% static "tasks/js/tasks.js" %}"></script>
{% endblock %}